<?php

declare(strict_types=1);

/**
 * Derafu: HTTP - Standard-Compliant HTTP Library with Extended Features.
 *
 * Copyright (c) 2026 Esteban De La Fuente Rubio / Derafu <https://www.derafu.dev>
 * Licensed under the MIT License.
 * See LICENSE file for more details.
 */

return [
    // 1xx Informational.
    'Continue' => 'Continuar',

    // 2xx Successful.
    'OK' => 'OK',
    'Created' => 'Creado',
    'Accepted' => 'Aceptado',
    'No Content' => 'Sin contenido',

    // 3xx Redirection.
    'Moved Permanently' => 'Movido permanentemente',
    'Found' => 'Encontrado',
    'See Other' => 'Ver otro',
    'Not Modified' => 'No modificado',
    'Temporary Redirect' => 'Redirección temporal',

    // 4xx Client Error.
    'Bad Request' => 'Solicitud incorrecta',
    'Unauthorized' => 'No autorizado',
    'Payment Required' => 'Pago requerido',
    'Forbidden' => 'Prohibido',
    'Not Found' => 'No encontrado',
    'Method Not Allowed' => 'Método no permitido',
    'Not Acceptable' => 'No aceptable',
    'Request Timeout' => 'Tiempo de espera agotado',
    'Conflict' => 'Conflicto',
    'Gone' => 'Ya no disponible',
    'Payload Too Large' => 'Contenido demasiado grande',
    'Unsupported Media Type' => 'Tipo de medio no soportado',
    'Unprocessable Content' => 'Contenido no procesable',
    'Locked' => 'Bloqueado',
    'Too Many Requests' => 'Demasiadas solicitudes',

    // 5xx Server Error.
    'Internal Server Error' => 'Error interno del servidor',
    'Not Implemented' => 'No implementado',
    'Bad Gateway' => 'Puerta de enlace incorrecta',
    'Service Unavailable' => 'Servicio no disponible',
    'Gateway Timeout' => 'Tiempo de espera de la puerta de enlace agotado',
    'Insufficient Storage' => 'Almacenamiento insuficiente',
    'Unknown Error' => 'Error desconocido',

    // Messages of the exceptions.
    'Bad request.' =>
        'Solicitud incorrecta.',
    'Too many requests.' =>
        'Demasiadas solicitudes.',
    'Route match not found. Ensure RouterMiddleware is executed before using the $request->route() method.' =>
        'No se encontró la ruta resuelta. Asegúrate de que RouterMiddleware se ejecute antes de usar el método $request->route().',
    'Session not found.' =>
        'No se encontró la sesión.',
    'Flash messages not found.' =>
        'No se encontraron los mensajes flash.',
    'No response was generated by the middleware chain.' =>
        'La cadena de middlewares no generó ninguna respuesta.',
    'Handler of type string {handler} is invalid.' =>
        'El manejador de tipo string {handler} es inválido.',
    'Unsupported handler type: {type}.' =>
        'Tipo de manejador no soportado: {type}.',
    'The trusted proxy "{proxy}" is not valid: it must be an IP address, a range (CIDR) or one of: {shortcuts}.' =>
        'El proxy de confianza "{proxy}" no es válido: debe ser una dirección IP, un rango (CIDR) o uno de: {shortcuts}.',
    'The header name "{header}" is not valid.' =>
        'El nombre de encabezado "{header}" no es válido.',
    'Cannot fall back to plain text: response is of type {type}, not string (JSON encoding failed: {reason}).' =>
        'No se puede usar texto plano como alternativa: la respuesta es de tipo {type}, no string (falló la codificación JSON: {reason}).',

    // Error pages.
    'The key of the error page "{key}" is not valid: it must be a status from 400 to 599 or "{default}".' =>
        'La clave de la página de error "{key}" no es válida: debe ser un estado de 400 a 599 o "{default}".',
    'The handler of the error page "{key}" is not valid: it must be a text that is not empty or a Closure.' =>
        'El manejador de la página de error "{key}" no es válido: debe ser un texto que no esté vacío o un Closure.',
];
