<?php

declare(strict_types=1);

/**
 * Derafu: HTTP - Standard-Compliant HTTP Library with Extended Features.
 *
 * Copyright (c) 2026 Esteban De La Fuente Rubio / Derafu <https://www.derafu.dev>
 * Licensed under the MIT License.
 * See LICENSE file for more details.
 */

namespace Derafu\TestsHttp\Service;

use Derafu\Http\Contract\ProblemDetailInterface;
use Derafu\Http\Contract\ProblemFactoryInterface;
use Derafu\Http\Contract\ProblemHandlerInterface;
use Derafu\Http\Contract\ResponseInterface;
use Derafu\Http\Request;
use Derafu\Http\Service\RequestHandler;
use Derafu\Translation\Contract\TranslatableInterface;
use LogicException;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface as PsrResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Throwable;

/**
 * A chain of middlewares that ends without a response is reported with a
 * translatable error, and the same handler attends any number of requests.
 */
#[CoversClass(RequestHandler::class)]
#[UsesClass(Request::class)]
final class RequestHandlerTest extends TestCase
{
    public function testAChainWithoutAResponseIsATranslatableError(): void
    {
        $reported = null;

        $factory = $this->createStub(ProblemFactoryInterface::class);
        $factory->method('create')->willReturnCallback(
            function (Throwable $throwable) use (&$reported): ProblemDetailInterface {
                $reported = $throwable;

                return $this->createStub(ProblemDetailInterface::class);
            }
        );
        $problemHandler = $this->createStub(ProblemHandlerInterface::class);
        $problemHandler->method('handle')->willReturn($this->createStub(ResponseInterface::class));

        (new RequestHandler($factory, $problemHandler))->handle(new Request('GET', 'http://localhost/'));

        $this->assertInstanceOf(LogicException::class, $reported);
        $this->assertInstanceOf(TranslatableInterface::class, $reported);
        $this->assertSame('No response was generated by the middleware chain.', $reported->getMessage());
    }

    public function testTheSameHandlerAttendsManyRequests(): void
    {
        $response = $this->createStub(PsrResponseInterface::class);

        $first = new class () implements MiddlewareInterface {
            public function process(
                ServerRequestInterface $request,
                RequestHandlerInterface $handler
            ): PsrResponseInterface {
                return $handler->handle($request);
            }
        };
        $last = new class ($response) implements MiddlewareInterface {
            public function __construct(private readonly PsrResponseInterface $response)
            {
            }

            public function process(
                ServerRequestInterface $request,
                RequestHandlerInterface $handler
            ): PsrResponseInterface {
                return $this->response;
            }
        };

        $handler = new RequestHandler(
            $this->createStub(ProblemFactoryInterface::class),
            $this->createStub(ProblemHandlerInterface::class),
            $first,
            $last
        );
        $request = new Request('GET', 'http://localhost/');

        $responses = [
            $handler->handle($request),
            $handler->handle($request),
            $handler->handle($request),
        ];

        $this->assertSame([$response, $response, $response], $responses);
    }
}
