# Example routes.

- route: /
  handler: '%kernel.project_dir%/README.md'
  name: homepage

- route: error
  handler: '%kernel.project_dir%/templates/error.html.twig'
  name: errorpage

# - route: /api
#   handler: 'Derafu\Http\Controller\ApiController::index'

# - route: /docs
#   handler: 'Derafu\Http\Controller\DocsController::index'
