# Example services.

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Derafu\Http\Controller\:
        resource: '../src/Controller/'
        public: true

    Psr\Http\Server\RequestHandlerInterface:
        class: Derafu\Http\Service\RequestHandler
        public: true
        arguments:
            $middlewares:
                - '@Derafu\Http\Middleware\StaticFilesMiddleware'
                - '@Derafu\Http\Middleware\RequestFactoryMiddleware'
                - '@Derafu\Http\Middleware\RouterMiddleware'
                - '@Derafu\Http\Middleware\DispatcherMiddleware'
                - '@Derafu\Http\Middleware\ResponseNormalizerMiddleware'

    Derafu\Http\Middleware\StaticFilesMiddleware:
        arguments:
            $directory: '%kernel.project_dir%/public/static'
    Derafu\Http\Middleware\RequestFactoryMiddleware: ~
    Derafu\Http\Middleware\RouterMiddleware: ~
    Derafu\Http\Middleware\DispatcherMiddleware: ~
    Derafu\Http\Middleware\ResponseNormalizerMiddleware: ~

    Derafu\Http\Contract\RequestFactoryInterface:
        class: Derafu\Http\Factory\RequestFactory

    Derafu\Routing\Contract\RouterInterface:
        class: Derafu\Routing\Router
        arguments:
            $parsers:
                - '@Derafu\Routing\Parser\StaticParser'
                - '@Derafu\Routing\Parser\FileSystemParser'
            $routes: '%routes%'

    Derafu\Routing\Parser\StaticParser: ~

    Derafu\Routing\Parser\FileSystemParser:
        arguments:
            $directories:
                - '%kernel.project_dir%/templates/pages'
            $extensions: ['.html.twig', '.md']

    Derafu\Http\Contract\DispatcherInterface:
        class: Derafu\Http\Service\Dispatcher

    Derafu\Http\Contract\ProblemHandlerInterface:
        class: Derafu\Http\Service\ProblemHandler

    Derafu\Http\Contract\ProblemFactoryInterface:
        class: Derafu\Http\Factory\ProblemFactory

    Derafu\Http\Contract\SafeThrowableFactoryInterface:
        class: Derafu\Http\Factory\SafeThrowableFactory

    Derafu\Renderer\Contract\RendererInterface:
        factory: ['Derafu\Renderer\Factory\RendererFactory', 'create']
        arguments:
            $options:
                engines: ['twig', 'markdown']
                paths: ['%kernel.project_dir%/templates']
